### ISSUE TITLE
Which api are you using?

### ISSUE THREAD

**Issue by tonymuu** [lullius/pylibby#2]
I see you are getting mp3 files from `https://sentry-read.svc.overdrive.com/...`. Which API/service is this? On the overdrive official api docs I couldn't find something similar.

**Comment by tonymuu** [comment]
Thank you! This is pretty neat and fits my need perfectly (I'm trying to put audiobooks on my Garmin music watch). 

I'm curious to know if this could be a long term solution. Why hasn't Libby/Overdrive put some restrictions on this API? Looks like it could be abused.

**Comment by lullius** [comment]
I like to listen on unsupported devices as well, it's one of the reasons I made this. The tool doesn't allow the user to do anything that the Libby app can't already do. It's basically just the Libby app in CLI form. You will always need to have a valid library card and to have borrowed the books. My intention was to make it easier for people to enjoy the books they have borrowed in the way they prefer.

How long it lasts is hard to say. Changes happen all the time. They may or may not put restrictions in place. Maybe there already is some form of rate limiting, I wouldn't know. Everything can be abused unfortunately, including the official Libby app.
