### ISSUE TITLE
[suggestion] Code formatting

### ISSUE THREAD

**Issue by ping** [lullius/pylibby#21]
The current code in pylibby.py is not PEP8 compliant and kinda makes changes and enhancements difficult.

I would like to recommend that [black](https://github.com/psf/black/) ([docs](https://black.readthedocs.io/en/stable/)) be used to format the code and if possible, to also set up [pre-commit hooks](https://black.readthedocs.io/en/stable/integrations/source_version_control.html) to automate this process for devs.

**Comment by lullius** [comment]
Thanks for the suggestion, added in 256afe690b1390d417cf1ab4f334cc51a3243dbf.
